# Generated by Django 4.2.1 on 2023-06-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('valor_compra', models.IntegerField()),
                ('valor_venta', models.IntegerField()),
                ('valor_ganancia', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50)),
                ('email_proveedor', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=160)),
                ('telefono', models.CharField(max_length=20)),
                ('num_identificacion', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=256)),
                ('rol', models.CharField(max_length=1)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id_detventa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.producto')),
            ],
            options={
                'db_table': 'detalles_venta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesCompra',
            fields=[
                ('id_detcompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.producto')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.proveedor')),
            ],
            options={
                'db_table': 'detalles_compra',
                'managed': True,
            },
        ),
    ]
