# Generated by Django 4.2.1 on 2023-06-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_detallesventa_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescompra',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.producto'),
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.proveedor'),
        ),
    ]
