# Generated by Django 4.2.1 on 2023-06-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20230603_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.producto'),
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.proveedor'),
        ),
        migrations.AlterField(
            model_name='detallesventa',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.producto'),
        ),
    ]
